### ISSUE TITLE
Given an event/trigger, I would like a way to express that an action should run on a set of hosts

### ISSUE THREAD

**Issue by ghost** [tristanfisher/yams#26]
It would be useful to be able to be able to run a SQL query and then act on hosts based on the result.  Multiple actions, triggers, and host specifications must be allowed.

note: that quotations around `x: "y"` v. `a: b` parse equally due to YAML. 

What I'm trying to express is that "given some triggering event, run a given set of actions on all matching hosts that I query."

e.g. one of the following syntaxes:  

A) flatter action/trigger/hosts

```
action: 
    shell: "cd /srv/website; git pull origin release"
trigger: 
    plugin: "github"
        repo: "github.com/tristanfisher/yams"
        event: "push"
        detail:
            branch: release
hosts: 
    yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"
```

or maybe the syntax could be:

B)  indented under action header:

```
action: 
    shell: "cd /srv/website; git pull origin release"
    trigger: 
        plugin: "github"
            repo: "github.com/tristanfisher/yams"
            event: "push"
            detail:
                branch: release
    hosts: 
        yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"
```

C) trigger -> action -> hosts

```
trigger: 
    plugin: "github"
        repo: "github.com/tristanfisher/yams"
        event: "push"
        detail:
            branch: release
    action: 
        shell: "cd /srv/website; git pull origin release"
    hosts:
        yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"
```

D) trigger -> host -> actions

```
trigger: 
    plugin: "github"
        repo: "github.com/tristanfisher/yams"
        event: "push"
        detail:
            branch: release
    hosts:
        yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"
    action: 
        shell: "cd /srv/website; git pull origin release"
```

---

note that eventually, boolean expressions must be allowed, e.g. 

```
trigger:
    plugin: "x"
       ....
    BOOLEAN: AND
    plugin: "y"
        ....
```

to express things like "if we are seeing increase page load times from our metrics AND people are complaining on twitter..."

**Comment by ghost** [comment]
E) with a name inclusion:

```
name: "do a git pull on all the webservers if we push on the release branch on github"
trigger: 
    plugin: "github"
        repo: "github.com/tristanfisher/yams"
        event: "push"
        detail:
            branch: release
    hosts:
        yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"
    action: 
        shell: "cd /srv/website; git pull origin release"
```

**Comment by ghost** [comment]
F) with name inclusion, flatter namespace, and boolean expressed:

```
name: "do a git pull on all the webservers if we push on the release branch on github and it's Tuesday afternoon"
trigger: 
    plugin: "github"
        repo: "github.com/tristanfisher/yams"
        event: "push"
        detail:
            branch: release
    BOOLEAN: AND
    plugin: "time"
        day: Tuesday
        hour: > 1200
hosts:
    yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"
action: 
    shell: "cd /srv/website; git pull origin release"
```

**Comment by tristanfisher** [comment]
@c-h-russell-walker brought up a great point of what happens if there's not an explicit 'trigger' action.

This would make the case of `E)` better structured and obvious in meaning, but lumping in a boolean expression has confusing consequences:

```
trigger: 
    plugin: "github"
        repo: "github.com/tristanfisher/yams"
        event: "push"
        detail:
            branch: release
    AND
    plugin: "other plugin"
    hosts:
        yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"
    action: 
        shell: "cd /srv/website; git pull origin release"
```

in this case, the 'flatter' first-level namespace of F allows for more coherent boolean expr, but comes with the consequence that `trigger` on ad-hoc commands would be an implicit True.

I'm cool with this though as the syntax getting an implicit "if not a trigger, then just run" allows for meta-expression chaining of "if the previous step in my logic did not fail, do this action on these hosts."

**Comment by tristanfisher** [comment]
And from feedback from @colinhoglund, the another syntax that could work is 

B+F):

```
event:
    name: "do a git pull on all the webservers if we push on the release branch on github and it's Tuesday afternoon"
    action:
        shell: "cd /srv/website; git pull origin release"
    trigger: 
        plugin: "github"
            repo: "github.com/tristanfisher/yams"
            event: "push"
            detail:
                branch: release
        BOOLEAN: AND
        plugin: "time"
            day: Tuesday
            hour: > 1200
    hosts:
        yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"  
```

**Comment by tristanfisher** [comment]
Going with F), but the ordering of name->action->trigger->hosts when stored on disk:

```
name: "do a git pull on all the webservers if we push on the release branch on github and it's Tuesday afternoon"
action:
    shell: "cd /srv/website; git pull origin release"
trigger: 
    plugin: "github"
        repo: "github.com/tristanfisher/yams"
        event: "push"
        detail:
            branch: release
    BOOLEAN: AND
    plugin: "time"
        day: Tuesday
        hour: > 1200
hosts:
    yams_database: "SELECT hostname FROM hosts WHERE profile = webserver"        
```

The sort/display order can be trivially changed later, but this seems to make the most sense as a declarative statement when writing "by hand."

Alternatively, this could be thought of as:

  if: git push to release AND tuesday after 12
  then: git pull on $hosts

(thanks @colinhoglund)
