### ISSUE TITLE
YAMS api needs a way to dynamically chain load settings

### ISSUE THREAD

**Issue by tristanfisher** [tristanfisher/yams#34]
This is really pertinent to the plugin system -- say that someone does a rackspace plugin and needs rackspace config vars.  

If we just slurp in a yaml config file, it will just be a blob that we have to target.  This means hard to upgrade due to git diffs.

Alternatively, we could separate the third-party/plugin system to a config file we call from our main configuration.  To do this right, it also means having to come up with a syntax in yaml for declaring the chain option names.  Maybe this means looking in a predictable place like:

`config.yml` or `config_local.yml`:

```
<<plugin_name>>:
    some_key: 
        config_name: some_file_name.yml:${some_val}
        envvar_name: YAMS_<<PLUGIN_NAME>>_KEY
        default: some_value
```
